module.exports = {
    SUCCESS: "success",
    FAIL: "fail",
    ERROR: "error",
    UNDEFINED: "undefined",
    ACTIVE: 'active',
    DEACTIVE: 'deactive',
    PAID: 'paid',
    ADMIN: 'admin',


    MESSAGE: {
        AUTHENTICATION_TOKEN_FAIL: "Invalid token!",
        AUTH_ACCESS_FAIL: "You are not authrized person to access!",
        NO_TOKEN_PROVIDED: "No token provided!",
        REQUIRED_FIELDS_MISSING: "Required fields are missing!",
        EMAIL_EXIST: 'Email already exists please try with another email!',
        EMAIL_ALREADY_EXIST: "Email is already exist!",
        ADDED_SUCCESSFULLY: "added successfully!!!",
        IS_UPDATED_SUCCESSFULLY: "is Updated Successfully!!!",
        NOT_FOUND_BY_ID: "not found with ID ",
        NOT_FOUND_BY_TYPE: "not found with product type ",
        DATA_FOUND: "Data found",
        DATA_NOT_FOUND: "Data not found",
        FOUND_SUCCESSFULLY: "found successfully!",
        DELETE_SUCCESSFULLY: "deleted successfully!",
        NOT_FOUND: "not found!",
        ERROR_OCCURRED: "Some error occurred while retrieving data",
        INVALID_PASSWORD: "Invalid password!",
        LOGIN_SUCESSFULLY: 'Login success!',
        EMAIL_INVALID: 'Incorrect Email',
        REGISTER_SUCCESSFULLY: 'Register successfully!!!',
        PASSOWRD_INVALID: 'Incorrect Password',
        USER_NOT_FOUND: 'User not found!',
        EMAIL_REQUIRED: 'Email address is required',
        SKILL_EXIST: 'Skill already exists please try with another skill!',
        CATEGORY_RECORD_EXIST: 'You can not delete this Category. Please first delete existing records with this Category.',
        Data_GET: 'Data not get',
        ACTIVE_SUCCESSFULLY: 'active successfully!!!',
        IMG_UPLOAD_SUCCESSFULLY: 'image upload successfully',
        IMAGE_NOT_FOUND: 'Image not found',
        FAILED_ADDED_IMAGE: 'Fail to added image..!',
        IMAGE_DELETE_SUCCESSFULLY: 'Image deleted successfully',
        FOLLOW_SUCCESSFULLY: 'follow successfully ..!!!',
        UNFOLLOW_SUCCESSFULLY: 'unfollow successfully ..!!!',
        ALREADY_FOLLOWED: 'you are already followed..!!!',
        U_MUST_FOLLOW_FIRST: 'you must follow first..!!!',
        FAIL_TO_GET_EVENT_POINT: 'Fail to get user eventPoints',
        FAIL_TO_UPDATE_EVENT_POINT: 'Fail to update user eventPoints',
        INVALID_PRODUCT_ID: 'Please enter valid product id ..!!',
        INVALID_BRAND_ID: 'Please enter valid brand id ..!!',
        INVALID_CATEGORY_ID: 'Please enter valid category id ..!!',
        INVALID_USER_ID: 'Please enter valid user id ..!!',
        STATUS_UPDATE_SUCCESSFULLY: 'status update succussfully ...!! '
    },
    COLLECTION: {
        USER: "User ",
        SOCIETY: "Society ",
        COMPLAINT: "Complaint ",
        POSITIVETHOUGHT: "PositiveThought ",
        ANNOUNCEMENT: "Announcement ",
        EVENT: "Event ",
        NOTICE: "Notice ",
        DISCUSSION: "Discussion ",
        FAQ: "FAQ ",
        GALLERY: "Gallery ",
        EXPENSEINCOME : "Expense Income ",
    }
}